const citas = [
  { cita: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", autor: "John Lennon" },
  { cita: "El éxito es aprender a ir de fracaso en fracaso sin desesperarse.", autor: "Winston Churchill" },
  { cita: "Lo que no te mata, te hace más fuerte.", autor: "Friedrich Nietzsche" },
  { cita: "Pienso, luego existo.", autor: "René Descartes" },
  { cita: "La imaginación lo es todo. Es la vista previa de las próximas atracciones de la vida.", autor: "Albert Einstein" },
  { cita: "El conocimiento es poder.", autor: "Francis Bacon" },
  { cita: "No cuentes los días, haz que los días cuenten.", autor: "Muhammad Ali" },
  { cita: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", autor: "Nelson Mandela" },
  { cita: "Sé el cambio que quieres ver en el mundo.", autor: "Mahatma Gandhi" },
  { cita: "La vida es realmente simple, pero insistimos en hacerla complicada.", autor: "Confucio" },
  { cita: "El hombre está condenado a ser libre.", autor: "Jean-Paul Sartre" },
  { cita: "El futuro pertenece a quienes creen en la belleza de sus sueños.", autor: "Eleanor Roosevelt" },
  { cita: "La mejor manera de empezar algo es dejar de hablar de ello y comenzar a hacerlo.", autor: "Walt Disney" },
  { cita: "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor: "John D. Rockefeller" },
  { cita: "El dinero no puede comprar la vida.", autor: "Bob Marley" },
  { cita: "El tiempo es oro.", autor: "Benjamin Franklin" },
  { cita: "Haz el amor y no la guerra.", autor: "John Lennon" },
  { cita: "Nunca soñé con el éxito. Trabajé para alcanzarlo.", autor: "Estée Lauder" },
  { cita: "El fracaso es éxito si aprendemos de él.", autor: "Malcolm Forbes" },
  { cita: "No hay camino para la paz, la paz es el camino.", autor: "Mahatma Gandhi" },
  { cita: "El que tiene un porqué para vivir puede soportar casi cualquier cómo.", autor: "Friedrich Nietzsche" },
  { cita: "La verdadera sabiduría está en reconocer la propia ignorancia.", autor: "Sócrates" },
  { cita: "El arte de vencer se aprende en las derrotas.", autor: "Simón Bolívar" },
  { cita: "El secreto de la felicidad no es hacer siempre lo que se quiere, sino querer siempre lo que se hace.", autor: "Tolstói" },
  { cita: "La lectura es para la mente lo que el ejercicio es para el cuerpo.", autor: "Joseph Addison" },
  { cita: "El poder tiende a corromper, y el poder absoluto corrompe absolutamente.", autor: "Lord Acton" },
  { cita: "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene.", autor: "Henry Ford" },
  { cita: "Si quieres vivir una vida feliz, átala a una meta, no a personas o cosas.", autor: "Albert Einstein" },
  { cita: "El hombre nunca sabe de lo que es capaz hasta que lo intenta.", autor: "Charles Dickens" },
  { cita: "Todo lo que se puede imaginar es real.", autor: "Pablo Picasso" },
  { cita: "El amor consuela como el resplandor del sol después de la lluvia.", autor: "William Shakespeare" },
  { cita: "Elige un trabajo que te guste y no tendrás que trabajar ni un día de tu vida.", autor: "Confucio" },
  { cita: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", autor: "Aristóteles" },
  { cita: "Los que no pueden recordar el pasado están condenados a repetirlo.", autor: "George Santayana" },
  { cita: "La mente es como un paracaídas: solo funciona si se abre.", autor: "Albert Einstein" },
  { cita: "El conocimiento habla, pero la sabiduría escucha.", autor: "Jimi Hendrix" },
  { cita: "Los hombres geniales comienzan grandes obras, los hombres trabajadores las terminan.", autor: "Leonardo da Vinci" },
  { cita: "La música expresa lo que no puede ser dicho y aquello sobre lo que es imposible permanecer en silencio.", autor: "Victor Hugo" },
  { cita: "La mayor gloria no es nunca caer, sino levantarse siempre.", autor: "Nelson Mandela" },
  { cita: "Cambia tus pensamientos y cambiarás tu mundo.", autor: "Norman Vincent Peale" },
  { cita: "El valor es resistencia al miedo, dominio del miedo, no ausencia del miedo.", autor: "Mark Twain" },
  { cita: "El hombre sabio querrá estar siempre con quien sea mejor que él.", autor: "Platón" },
  { cita: "La verdad os hará libres.", autor: "Jesucristo" },
  { cita: "El hombre muere cuando deja de soñar.", autor: "Gabriel García Márquez" },
  { cita: "El talento gana juegos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", autor: "Michael Jordan" },
  { cita: "Nunca interrumpas a tu enemigo cuando está cometiendo un error.", autor: "Napoleón Bonaparte" },
  { cita: "El hombre se descubre cuando se mide contra un obstáculo.", autor: "Antoine de Saint-Exupéry" },
  { cita: "El secreto de la creatividad es saber cómo esconder tus fuentes.", autor: "Albert Einstein" },
  { cita: "Nadie puede hacerte sentir inferior sin tu consentimiento.", autor: "Eleanor Roosevelt" },
  { cita: "El único modo de hacer un gran trabajo es amar lo que haces.", autor: "Steve Jobs" }
];
